#
# Makefile for the s3c framebuffer driver
#

obj-$(CONFIG_FB_S3C)		+= s3cfb.o
obj-$(CONFIG_FB_S3C)		+= s3cfb_spi.o
obj-$(CONFIG_PLAT_S3C64XX)	+= s3cfb_fimd4x.o
obj-$(CONFIG_PLAT_S5P64XX)	+= s3cfb_fimd5x.o
obj-$(CONFIG_PLAT_S5PC1XX)	+= s3cfb_fimd5x.o
obj-$(CONFIG_FB_S3C_TFT480272)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_HSD480272)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_TFT800480)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_S70T800480)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_W50I800480)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_T240320)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_TFT640480)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_VGA1024768)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_VGA800600)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_VGA640480)	+= s3c_mini6410.o
obj-$(CONFIG_FB_S3C_EZVGA800600)+= s3c_mini6410.o
